# Generated by Django 4.0.4 on 2022-05-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ori_code', models.CharField(max_length=7)),
                ('agency_name', models.CharField(max_length=25)),
                ('agency_state_name', models.CharField(max_length=6)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=3)),
                ('card', models.CharField(max_length=14)),
                ('category', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=8)),
            ],
        ),
    ]
