# Generated by Django 4.0.4 on 2022-05-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_year', models.IntegerField(choices=[(1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)])),
                ('ori', models.CharField(max_length=50)),
                ('ncic_agency_name', models.CharField(max_length=50)),
                ('state_abbr', models.CharField(max_length=2)),
                ('county_name', models.CharField(max_length=50)),
                ('msa_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RetA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ori_code', models.CharField(max_length=7)),
                ('agency_name', models.CharField(max_length=25)),
                ('core_city', models.BooleanField()),
                ('agency_state_name', models.CharField(max_length=6)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=3)),
                ('card', models.CharField(max_length=14)),
                ('category', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
    ]
